export const profileEditStyle = {
  imgBoxStyle: {
    align: 'center',
    direction: 'column',
    h: '328px',
    m: { base: '100px 10px 0 0', md: '60px 45px 0 0', lg: '50px 45px 0 78px' },
    zIndex: '1',
  },
  imgStyle: {
    borderRadius: 'full',
    dropShadow: '-9px 8px 8px rgba(68, 73, 85, 0.4)',
    boxSize: { base: '158px', md: '230', lg: '256' },
    mixBlendMode: 'normal',
  },
  linkImage: {
    border: '1px solid #444955',
    borderRadius: '2px',
    color: '#444955',
    fontSize: '12px',
    fontWeight: '400',
    h: '36px',
    w: '192px',
    lineHeight: '35px',
    mt: '18px',
    placeholder: 'Insira um link da sua foto',
    focusBorderColor: 'none',
    focus: {
      boxShadow: 'none',
    },
  },
  h1Form: {
    color: '#3d495c',
    fontSize: '16px',
    fontWeight: '700',
    lineHeight: '150%',
  },
  textForm: {
    color: '#3d495c',
    fontSize: '12px',
    fontWeight: '400',
    lineHeight: '150%',
    mb: '6px',
  },
  inputForm: {
    borderBottom: '1px solid #3d495c',
    color: '#303030',
    fontFamily: 'verdana sans-serif',
    fontSize: '14px',
    fontWeight: '400',
    h: '37px',
    w: '288px',
    lineHeight: '150%',
    mb: '23px',
    pl: '8px',
    bgColor: 'white',
    focusBorderColor: 'none',
    focus: {
      boxShadow: 'none',
    },
    _placeholder: {
      color: '#c5c9ce',
      fontFamily: 'verdana sans-serif',
      fontsize: '14px',
      fontWeight: '400',
      lineHeight: '150%',
    },
  },
  textAreaForm: {
    borderBottom: '1px solid #3d495c',
    color: '#303030',
    fontSize: '14px',
    fontWeight: '400',
    h: '106px',
    w: { base: '100%', lg: '490px' },
    lineHeight: '150%',
    mb: '31px',
    resize: 'none',
    bgColor: 'white',
    focusBorderColor: 'none',
    focus: {
      boxShadow: 'none',
    },
    _placeholder: {
      color: '#c5c9ce',
      fontsize: '14px',
      fontWeight: '400',
      lineHeight: '150%',
    },
  },
  buttonForm: {
    bg: '#003be5',
    borderRadius: '100px',
    color: 'white',
    fontSize: '14px',
    fontWeight: '700',
    h: '40px',
    w: '152px',
    letterSpacing: '0.03em',
    textAlign: 'center',
    textTransform: 'uppercase',
    _disabled: { bg: 'gray' },
  },
};
